### PR TITLE
Using GitHub PR Number

### PR DESCRIPTION
**Pull request by ThomasMonnier**
Modifications are:
1. GitHub PR Number

When `only_cancel_run_if_commit_is_using_pr_branch` is set to true, we'll use the GitHub PR number to identify the dbt cloud runs to delete instead of the GitHub PR sha, which is far more complicated and raised some issues. Indeed, the changement of the sha when a rebasing (to the main/master branch) occurs implies an impossibility for the code to spot the right dbt cloud runs.

Instead of that, the user can provide the GitHub PR number which is an environment variable:
`github_pr_number: ${{ github.event.number }}`

And with dbt cloud API v2, we can also extract the PR number thanks to the data stored in `trigger`:
`run_git_pr_number = run['trigger']['github_pull_request_id']`

We just have to be careful that `github_pr_number` is a string whereas `run_git_pr_number` is an integer.

Therefore, some piece of code can be simplified quite easily with that.

2. Max Numbers of recent dbt cloud runs

Instead of having 10 as the definitive value of the number of recent runs to search for, I stored this value as a non-required variable ("10" by default). For some cases such as mine, I need to go back sometimes to at least 50 runs.

3. Next step for the next PR: [Change the deprecating save state and set output commands to what is recommended by GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

-- 
Thanks for having the time to review my PR. If you want to test it, you can refer to [the latest release](https://github.com/marketplace/actions/dbt-cloud-cancel-ci-job-runs-action) on Marketplace.

### CODE REVIEW

**Comment by ThomasMonnier** [comment]
It seems that there is a problem to log the dbt cloud runs that have been cancelled. I don't know why, I'll keep looking.

**Comment by ThomasMonnier** [comment]
Step 3 done thanks to `subprocess.call`! Nothing has to be changed in the action file for it to work.

Therefore, here is an example of an action yml file with the latest release:

```
name: CI Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_QUIET: 2

jobs:
  cancel:
    name: cancel dbt cloud runs
    runs-on: self-hosted
    container: ubuntu:20.04

    steps:
       # running the step to cancel another other CI job runs that are running except the latest
      - name: dbt Cloud Cancel CI Job Runs Action
        uses: ThomasMonnier/dbt-cloud-cancel-running-ci-job-action@v1.7
        id: cancel_stale_ci_runs
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
          dbt_cloud_account_id: ${{ secrets.DBT_ACCOUNT_ID }}
          dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}
          github_pr_number: ${{ github.event.number }}
          max_runs: "50"
          only_cancel_run_if_commit_is_using_pr_branch: true
          github_repo_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Logging if no CI runs were cancelled
        if: steps.cancel_stale_ci_runs.outputs.cancelled_jobs_flag == 'False'
        run: echo "No dbt Cloud CI job run(s) were cancelled"
          
      # logging if there was a job run(s) cancelled or not
      - name: Logging if there was a CI run that was cancelled
        if:  steps.cancel_stale_ci_runs.outputs.cancelled_jobs_flag == 'True'
        run: |
          echo "A dbt Cloud CI job run(s) was cancelled due to a new CI run being triggered"
          echo "The following job runs were cancelled ${{ steps.cancel_stale_ci_runs.outputs.cancelled_dbt_cloud_job_runs }}"
          
      # if there a job run(s) was cancelled, we grab the outputted markdown and put it into a PR comment for logging
      - name: PR comment with Job Run Cancelation Information
        uses: mshick/add-pr-comment@v1
        if:  steps.cancel_stale_ci_runs.outputs.cancelled_jobs_flag == 'True'
        with:
          message: |
            ${{ steps.cancel_stale_ci_runs.outputs.cancelled_dbt_cloud_job_runs_markdown }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false # This is the default
```

**Comment by Stevedow99** [comment]
@ThomasMonnier oh wow - love the thought process of using PR number instead of sha. That's much cleaner. Going to do some testing and review and hope to have it merged and in a release soon. Thanks for all the work on that!

**Comment by Stevedow99** [comment]
1. Tested on a single running job with one in queue and worked accordingly
2. Tested with a running job and multiple queued jobs and worked accordingly
3. Tested on a singular run with nothing to cancel and worked accordingly
4. Tested on a brand new CI job with no previous runs and worked accordingly

Merging to main! I will update the docs and remove the `github_repo_token` input and then create release v1.2

**Comment by Stevedow99** [comment]
Updated the action on the marketplace to v1.2 and updated all the docs/stale code. Thanks for all the work on this @ThomasMonnier! The action is much cleaner and runs faster.

**Comment by ThomasMonnier** [comment]
Thanks a lot @Stevedow99 for having merged these contributions ! Happy to help.
I will delete my forked repository and my action on the marketplace in the next hours.

**Pull request merged**
